// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.2
// source: proto/options/options.proto

package options

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

func (x *YetiMessageOptions) YetiSerialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiMessageOptions) YetiName() string {
	return "YetiMessageOptions"
}

func (x *YetiMessageOptions) YetiKey() (string, error) {
	var err error
	t := time.Now()
	key := t.Format("20060102150405")
	return key, err
}
func (x *YetiFieldOptions) YetiSerialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiFieldOptions) YetiName() string {
	return "YetiFieldOptions"
}

func (x *YetiFieldOptions) YetiKey() (string, error) {
	var err error
	t := time.Now()
	key := t.Format("20060102150405")
	return key, err
}
