// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: proto/options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YetiMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *YetiMessageOptions) Reset() {
	*x = YetiMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_options_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YetiMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YetiMessageOptions) ProtoMessage() {}

func (x *YetiMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_options_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YetiMessageOptions.ProtoReflect.Descriptor instead.
func (*YetiMessageOptions) Descriptor() ([]byte, []int) {
	return file_proto_options_options_proto_rawDescGZIP(), []int{0}
}

type YetiFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryKey bool `protobuf:"varint,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
}

func (x *YetiFieldOptions) Reset() {
	*x = YetiFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_options_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YetiFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YetiFieldOptions) ProtoMessage() {}

func (x *YetiFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_options_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YetiFieldOptions.ProtoReflect.Descriptor instead.
func (*YetiFieldOptions) Descriptor() ([]byte, []int) {
	return file_proto_options_options_proto_rawDescGZIP(), []int{1}
}

func (x *YetiFieldOptions) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

var file_proto_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*YetiMessageOptions)(nil),
		Field:         52125,
		Name:          "yeti.proto.options.yeti_message_opts",
		Tag:           "bytes,52125,opt,name=yeti_message_opts",
		Filename:      "proto/options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*YetiFieldOptions)(nil),
		Field:         52125,
		Name:          "yeti.proto.options.yeti_field_opts",
		Tag:           "bytes,52125,opt,name=yeti_field_opts",
		Filename:      "proto/options/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional yeti.proto.options.YetiMessageOptions yeti_message_opts = 52125;
	E_YetiMessageOpts = &file_proto_options_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional yeti.proto.options.YetiFieldOptions yeti_field_opts = 52125;
	E_YetiFieldOpts = &file_proto_options_options_proto_extTypes[1]
)

var File_proto_options_options_proto protoreflect.FileDescriptor

var file_proto_options_options_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x79,
	0x65, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x59, 0x65, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x33, 0x0a, 0x10, 0x59, 0x65, 0x74,
	0x69, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x3a, 0x75,
	0x0a, 0x11, 0x79, 0x65, 0x74, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6f,
	0x70, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x9d, 0x97, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x79,
	0x65, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x59, 0x65, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0f, 0x79, 0x65, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4f, 0x70, 0x74, 0x73, 0x3a, 0x6d, 0x0a, 0x0f, 0x79, 0x65, 0x74, 0x69, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x9d, 0x97, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x79, 0x65, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x59, 0x65, 0x74, 0x69, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x79, 0x65, 0x74, 0x69, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x75, 0x76, 0x69, 0x6b, 0x62, 0x69, 0x73, 0x77, 0x61, 0x73, 0x2f,
	0x79, 0x65, 0x74, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_options_options_proto_rawDescOnce sync.Once
	file_proto_options_options_proto_rawDescData = file_proto_options_options_proto_rawDesc
)

func file_proto_options_options_proto_rawDescGZIP() []byte {
	file_proto_options_options_proto_rawDescOnce.Do(func() {
		file_proto_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_options_options_proto_rawDescData)
	})
	return file_proto_options_options_proto_rawDescData
}

var file_proto_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_options_options_proto_goTypes = []interface{}{
	(*YetiMessageOptions)(nil),          // 0: yeti.proto.options.YetiMessageOptions
	(*YetiFieldOptions)(nil),            // 1: yeti.proto.options.YetiFieldOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_proto_options_options_proto_depIdxs = []int32{
	2, // 0: yeti.proto.options.yeti_message_opts:extendee -> google.protobuf.MessageOptions
	3, // 1: yeti.proto.options.yeti_field_opts:extendee -> google.protobuf.FieldOptions
	0, // 2: yeti.proto.options.yeti_message_opts:type_name -> yeti.proto.options.YetiMessageOptions
	1, // 3: yeti.proto.options.yeti_field_opts:type_name -> yeti.proto.options.YetiFieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_options_options_proto_init() }
func file_proto_options_options_proto_init() {
	if File_proto_options_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_options_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YetiMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_options_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YetiFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_options_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_options_options_proto_goTypes,
		DependencyIndexes: file_proto_options_options_proto_depIdxs,
		MessageInfos:      file_proto_options_options_proto_msgTypes,
		ExtensionInfos:    file_proto_options_options_proto_extTypes,
	}.Build()
	File_proto_options_options_proto = out.File
	file_proto_options_options_proto_rawDesc = nil
	file_proto_options_options_proto_goTypes = nil
	file_proto_options_options_proto_depIdxs = nil
}
