// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.2
// source: proto/options/options.proto

package options

import (
	yeti "github.com/sauvikbiswas/yeti"
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

func (x *YetiMessageOptions) New() yeti.Record {
	return &YetiMessageOptions{}
}

func (x *YetiMessageOptions) YetiSerialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiMessageOptions) YetiDeserialize(b []byte) error {
	return protojson.Unmarshal(b, x)
}

func (x *YetiMessageOptions) YetiType() string {
	return "YetiMessageOptions"
}

func (x *YetiMessageOptions) YetiKey() (string, error) {
	var err error
	t := time.Now()
	key := t.Format("20060102150405")
	return key, err
}

func (x *YetiFieldOptions) New() yeti.Record {
	return &YetiFieldOptions{}
}

func (x *YetiFieldOptions) YetiSerialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiFieldOptions) YetiDeserialize(b []byte) error {
	return protojson.Unmarshal(b, x)
}

func (x *YetiFieldOptions) YetiType() string {
	return "YetiFieldOptions"
}

func (x *YetiFieldOptions) YetiKey() (string, error) {
	var err error
	t := time.Now()
	key := t.Format("20060102150405")
	return key, err
}
