//"github.com/sauvikbiswas/yeti/tests/proto/test""tests/proto/test"
// protoc -I=. --go_out=../protostruct test.proto
// protoc --proto_path=./tests/protosrc --proto_path=./proto/options  --go_out=./tests/protostruct --go_opt paths=source_relative $(find . -name '*.proto' -not -path "*scalapackage.proto")

// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.4
// source: proto/test/test.proto

package test

import (
	fmt "fmt"
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

func (x *TestProto) Serialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *TestProto) Key() (string, error) {
	t := time.Now()
	fileName := fmt.Sprintf("TestProto_%s.json", t.Format("20060102150405"))
	return fileName, nil
}
