// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.4
// source: proto/test/test.proto

package test

import (
	fmt "fmt"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *TestProto) YetiSerialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *TestProto) YetiName() string {
	return "TestProto"
}

func (x *TestProto) YetiKey() (string, error) {
	var err error
	if string(x.GetName()) == "" {
		return "", fmt.Errorf("name is not set")
	}
	key := x.GetName()
	return key, err
}
