// protoc -I=. --go_out=../protostruct test.proto

// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.4
// source: test.proto

package protostruct

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *TestProto) Serialize() ([]byte, error) {
	return protojson.Marshal(x)
}
