// protoc -I=. --go_out=../protostruct test.proto

// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.4
// source: test.proto

package protostruct

import (
	fmt "fmt"
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

func (x *TestProto) Serialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *TestProto) Key() (string, error) {
	t := time.Now()
	fileName := fmt.Sprintf("TestProto_%s.json", t.Format("20060102150405"))
	return fileName, nil
}
