//"github.com/sauvikbiswas/yeti/tests/proto/options""tests/proto/options"
// protoc -I=. --go_out=../../ options.proto

// Code generated by protoc-gen-go-yeti. DO NOT EDIT.
// versions:
// - protoc-gen-go-yeti v0.0.0
// - protoc             v4.23.4
// source: proto/options/options.proto

package options

import (
	fmt "fmt"
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

func (x *YetiMessageOptions) Serialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiMessageOptions) Key() (string, error) {
	t := time.Now()
	fileName := fmt.Sprintf("YetiMessageOptions_%s.json", t.Format("20060102150405"))
	return fileName, nil
}
func (x *YetiFieldOptions) Serialize() ([]byte, error) {
	return protojson.Marshal(x)
}

func (x *YetiFieldOptions) Key() (string, error) {
	t := time.Now()
	fileName := fmt.Sprintf("YetiFieldOptions_%s.json", t.Format("20060102150405"))
	return fileName, nil
}
